# Generated by Django 3.1.7 on 2021-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210428_1428'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='favorite_articles', to='articles.Article'),
        ),
    ]
