# Generated by Django 3.1.7 on 2021-05-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_verifycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='icon',
            field=models.ImageField(default='../../var/www/html/GameRecommend/templates/img/a.png', upload_to='../../var/www/html/GameRecommend/templates/img/'),
        ),
    ]
