# Generated by Django 3.1.7 on 2021-04-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlesgame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='content_html',
        ),
        migrations.AddField(
            model_name='article',
            name='content_md',
            field=models.TextField(default='default markdown content'),
            preserve_default=False,
        ),
    ]
