# Generated by Django 3.1.7 on 2021-05-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_fav_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesgame',
            name='index',
        ),
    ]
