# Generated by Django 3.1.7 on 2021-04-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_filemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='author',
        ),
    ]
