# Generated by Django 3.1.7 on 2021-04-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210408_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_brief',
            field=models.TextField(default='Default content brief'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='img_src',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
