# Generated by Django 3.1.7 on 2021-04-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210410_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img_src',
        ),
    ]
