# Generated by Django 3.1.7 on 2021-04-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_src',
            field=models.CharField(default='/path/to/img', max_length=100),
            preserve_default=False,
        ),
    ]
