# Generated by Django 3.1.7 on 2021-04-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_src',
            field=models.CharField(max_length=1000),
        ),
    ]
